image: node:24.2.0-alpine3.22

variables:
  PNPM_STORE_PATH: .pnpm-store

stages:
  - check
  - build

default:
  before_script:
    - npm install -g corepack@latest
    - corepack enable
    - corepack prepare pnpm@10.11.0 --activate
    - pnpm config set store-dir $PNPM_STORE_PATH
    - pnpm install

  cache:
    key:
      files:
        - pnpm-lock.yaml

    paths:
      - $PNPM_STORE_PATH

lint:
  stage: check

  script:
    - pnpm lint

test:
  stage: check

  script:
    - pnpm test

  coverage: /All files[^\|]*\|[^\|]*\s+([\d\.]+)/

  artifacts:
    untracked: false
    when: always
    access: all
    expire_in: "30 days"

    reports:
      junit:
        - "./**/junit.xml"

      coverage_report:
        coverage_format: cobertura
        path: "./**/cobertura-coverage.xml"

build:
  stage: build

  needs:
    - test

  script:
    - pnpm build
