image: node:23.11.0-alpine3.21

variables:
  PNPM_STORE_PATH: .pnpm-store

stages:
  - lint
  - build

default:
  before_script:
    - npm install -g corepack@latest
    - corepack enable
    - corepack prepare pnpm@10.11.0 --activate
    - pnpm config set store-dir $PNPM_STORE_PATH
    - pnpm install

  cache:
    key:
      files:
        - pnpm-lock.yaml

    paths:
      - $PNPM_STORE_PATH

lint:
  stage: lint

  script:
    - pnpm lint

build:
  stage: build

  script:
    - pnpm build
