// Accounts
export interface Account {
  name: string;
  full_name: string;
  registration_no: string;
  vat_no: string;
  vat_mode: string;
  vat_price_mode: string;
  company_name?: string;
  email?: string;
  phone?: string;
  web?: string;
  address_street?: string;
  address_street2?: string;
  address_city?: string;
  address_postcode?: string;
  address_country?: string;
  bank_account?: string;
  iban?: string;
  swift_bic?: string;
  currency?: string;
  unit_name?: string;
  vat_rate?: number;
  displayed_note?: string;
  invoice_note?: string;
  html_url?: string;
  url?: string;
  updated_at?: string;
  created_at?: string;
} 